// <auto-generated />
namespace Cinehive.HiveData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class movielatesttest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movielatesttest));
        
        string IMigrationMetadata.Id
        {
            get { return "202104101237458_movielatesttest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
